{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "import requests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Write the artist name here: lady gaga\n",
      "Write the song name here: born this way\n",
      "\n",
      "\n",
      "The lyrics is: \n",
      "It doesn't matter if you love him,Or capital H-I-M\n",
      "Just put your paws up'cause you were born this way, baby\n",
      "\n",
      "My mama told me when I was young\n",
      "We are all born superstars\n",
      "She rolled my hair and put my lipstick on\n",
      "\n",
      "In the glass of her boudoir\n",
      "\n",
      "\"there's nothin wrong with lovin who you are\"She said, \"'cause he made you perfect, babe\"\n",
      "\n",
      "\"so hold your head up girl and you'll go far,\n",
      "\n",
      "Listen to me when I say\"\n",
      "\n",
      "\n",
      "\n",
      "I'm beautiful in my way'cause god makes no mistakes\n",
      "\n",
      "I'm on the right track baby\n",
      "\n",
      "I was born this way\n",
      "\n",
      "Don't hide yourself in regret\n",
      "\n",
      "Just love yourself and you're set\n",
      "\n",
      "I'm on the right track babyI was born this way\n",
      "\n",
      "\n",
      "\n",
      "Ooo there ain't no other way\n",
      "\n",
      "Baby I was born this way\n",
      "\n",
      "Baby I was born this way\n",
      "\n",
      "Ooo there ain't no other way\n",
      "\n",
      "Baby I was born this way\n",
      "\n",
      "I'm on the right track baby\n",
      "\n",
      "I was born this way\n",
      "\n",
      "\n",
      "\n",
      "Don't be a drag - just be a queen\n",
      "\n",
      "Don't be a drag - just be a queen\n",
      "\n",
      "Don't be a drag - just be a queen\n",
      "\n",
      "Don't be!\n",
      "\n",
      "\n",
      "\n",
      "Give yourself prudence\n",
      "\n",
      "And love your friends\n",
      "\n",
      "Subway kid, rejoice your truth\n",
      "\n",
      "In the religion of the insecure\n",
      "\n",
      "I must be myself, respect my youth\n",
      "\n",
      "A different lover is not a sin\n",
      "\n",
      "Believe capital h-i-m (hey hey hey)\n",
      "\n",
      "I love my life I love this record and\n",
      "\n",
      "Mi amore vole fe yah (love needs faith)\n",
      "\n",
      "\n",
      "\n",
      "I'm beautiful in my way'cause god makes no mistakes\n",
      "\n",
      "I'm on the right track baby\n",
      "\n",
      "I was born this way\n",
      "\n",
      "Don't hide yourself in regret\n",
      "\n",
      "Just love yourself and you're set\n",
      "\n",
      "I'm on the right track baby\n",
      "\n",
      "I was born this way\n",
      "\n",
      "\n",
      "\n",
      "Ooo there ain't no other way\n",
      "\n",
      "Baby I was born this way\n",
      "\n",
      "Baby I was born this way\n",
      "\n",
      "Ooo there ain't no other way\n",
      "\n",
      "Baby I was born... I'm on the right track babyI was born this way\n",
      "\n",
      "\n",
      "\n",
      "Don't be a drag, just be a queen\n",
      "\n",
      "Whether you're broke or evergreen\n",
      "\n",
      "You're black, white, beige, chola descent\n",
      "\n",
      "You're lebanese, you're orient\n",
      "\n",
      "Whether life's disabilities\n",
      "\n",
      "Left you outcast, bullied, or teased\n",
      "\n",
      "Rejoice and love yourself today'cause baby you were born this way\n",
      "\n",
      "No matter gay, straight, or bi,Lesbian, transgendered life\n",
      "\n",
      "I'm on the right track baby\n",
      "\n",
      "I was born to survive\n",
      "\n",
      "No matter black, white or beigeChola or orient made\n",
      "\n",
      "I'm on the right track baby\n",
      "\n",
      "I was born to be brave\n",
      "\n",
      "\n",
      "\n",
      "I'm beautiful in my way'cause god makes no mistakes\n",
      "\n",
      "I'm on the right track baby\n",
      "\n",
      "I was born this way\n",
      "\n",
      "Don't hide yourself in regret\n",
      "\n",
      "Just love yourself and you're set\n",
      "\n",
      "I'm on the right track baby\n",
      "\n",
      "I was born this way\n",
      "\n",
      "\n",
      "\n",
      "ooh there ain't no other way\n",
      "\n",
      "I was born this way\n",
      "\n",
      "baby i was born this way\n",
      "\n",
      "ooh there ain't no other way\n",
      "\n",
      "I was born this way\n",
      "\n",
      "baby i was born this way\n",
      "\n",
      "\n",
      "\n",
      "I was born this way hey!\n",
      "\n",
      "I was born this way hey!\n",
      "\n",
      "I'm on the right track baby\n",
      "\n",
      "I was born this way hey!\n",
      "\n",
      "I was born this way hey!\n",
      "\n",
      "I was born this way hey!\n",
      "\n",
      "I'm on the right track baby\n",
      "\n",
      "I was born this way hey!\n",
      "\n"
     ]
    }
   ],
   "source": [
    "def get_lyrics():\n",
    "    base_url = \"https://api.lyrics.ovh/v1/\"\n",
    "    \n",
    "    print()\n",
    "    \n",
    "    artist_name=input('Write the artist name here: ')\n",
    "    song_title=input('Write the song name here: ')\n",
    "    \n",
    "    search_url = base_url + artist_name + '/' + song_title\n",
    "    \n",
    "    print()\n",
    "    print()\n",
    "    \n",
    "    req = requests.get(search_url)\n",
    "    dict_lyrics=req.json()\n",
    "    list_lyr=dict_lyrics['lyrics']\n",
    "    \n",
    "    if len(list_lyr) == 0 :\n",
    "        print(\"We haven't found a lyrics for your research.\")\n",
    "        print(\"Please verify that you haven't mispelled, or try changing your song.\")    \n",
    "        \n",
    "        #artist_name2=input('Write the artist name here: ')\n",
    "        #song_title2=input('Write the song name here: ')\n",
    "        #break\n",
    "        \n",
    "    else:\n",
    "        print('The lyrics is: ')\n",
    "        \n",
    "    \n",
    "    print( list_lyr )\n",
    "\n",
    "    return get_lyrics()\n",
    "\n",
    "print (get_lyrics())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import argparse\n",
    "parser = argparse.ArgumentParser()\n",
    "parser.add_argument(\"get info\", help=\"the function gives you the lyrics\")\n",
    "args = parser.parse_args()\n",
    "print(args.echo)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
